name: Laravel pint

on:
  pull_request:

jobs:
  laravel-pint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: "laravel-pint"
        uses: aglipanci/laravel-pint-action@v2
        with:
          testMode: true
          useComposer: true
