name: Run Pest Tests

on:
  - pull_request

jobs:
  pest:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        laravel: ["^13", "^12"]
        dependency-version: [prefer-stable]
        include:
          - laravel: "^13"
            php: 8.5
            testbench: 11.*
          - laravel: "^12"
            php: 8.2
            testbench: 10.*

    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.dependency-version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: curl, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, iconv
          coverage: none

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
          composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction

      - name: Execute tests
        run: vendor/bin/pest
